---
name: "Build & Test"
on:  # yamllint disable-line rule:truthy
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
jobs:
  unit:
    name: "Unit"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-go@v3"
        with:
          go-version: "^1.17"
      - uses: "authzed/actions/go-test@main"
